#!/bin/bash

#SBATCH --job-name=tensorflow-test
#SBATCH --output=job.%j.out
#SBATCH --cpus-per-task=16
#SBATCH --gres=gpu
#SBATCH --time=01:00:00
#SBATCH --partition=brown
#SBATCH --mail-type=FAIL,END

module load Anaconda3/2021.05
source activate p2_tensor

nvidia-smi --query-gpu=timestamp,power.draw,temperature.gpu,memory.used --format=csv --loop-ms=1000 > "./experiments/gpu/tensorflow/test.csv" & 
serverPID=$!
python ./src/training_tensorflow.py --dataset=SVHN --resnet_size=resnet50 --device=gpu --batch_size=128 --epochs=10 > "./experiments/gpu/tensorflow/test_py.csv"
kill $serverPID