#!/bin/bash

#SBATCH --job-name=pytorch-test
#SBATCH --output=job.%j.out
#SBATCH --cpus-per-task=16
#SBATCH --gres=gpu
#SBATCH --time=01:00:00
#SBATCH --partition=brown
#SBATCH --mail-type=FAIL,END

module load Anaconda3
source activate p2_torch

nvidia-smi --query-gpu=timestamp,power.draw,temperature.gpu,memory.used --format=csv --loop-ms=1000 > "./experiments/gpu/pytorch/test.csv" &
serverPID=$!
python ./src/training_pytorch.py --dataset=SVHN --resnet_size=resnet50 --device=gpu --batch_size=128 --epochs=10 --run=0
kill $serverPID