#!/bin/bash

#SBATCH --job-name=ivas-gpu-training    # Job name
#SBATCH --output=job.%j.out      # Name of output file (%j expands to jobId)
#SBATCH --cpus-per-task=8
#SBATCH --gres=gpu               # Schedule a GPU
#SBATCH --time=01:00:00          # Run time (hh:mm:ss) - run for one hour max
#SBATCH --partition=red,brown    # Run on either the Red or Brown queue

nvidia-smi --query-gpu=power.draw,temperature.gpu,memory.used --format=csv --loop-ms=5000 > ./experiments/pytorch/experiment-test.csv &
serverPID=$!
date +%Y-%m-%d_%H-%M-%S.%N > ./log
python ./src/training_tensorflow.py --dataset=CIFAR10 --resnet_size="resnet50" > ./log
date +%Y-%m-%d_%H-%M-%S.%N > ./log
kill serverPID